version: '3'
services:
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - internal_network
      - external_network
  db:
    restart: always
    image: postgis/postgis:12-master
    env_file:
      .env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - ./init_db_roles.sh:/docker-entrypoint-initdb.d/init_db_roles.sh
    ports:
      - "5432:5432"
    networks:
      - internal_network
      - external_network
  app:
    restart: always
    build: ./app
    working_dir: /app
    env_file:
      .env
    depends_on:
      - db
    networks:
      - internal_network
      - external_network
    expose:
      - "8080"

volumes:
  db-data:

networks:
  external_network:
  internal_network:
    internal: true
